いいね機能実装
shinonome-inc/backend-final-assignment-toki-Toki-Shiota- pull request #5
Opened 2023-03-05 06:19 UTC by Shiota620

2023-03-05 08:06 UTC, Shiota620 commented
![スクリーンショット (36)](https://user-images.githubusercontent.com/107160473/222949173-5a227c37-fada-4007-a0cc-f7c2b68714c8.png)

2023-03-05 08:37 UTC, Yamakou621 reviewed
確認お願いします！

2023-03-05 08:37 UTC, Yamakou621 commented on templates/tweets/home.html
> +<a href="{% url 'accounts:logout' %}">ログアウト</a>
base.htmlで既に表示されているのでいりません。

2023-03-05 08:37 UTC, Yamakou621 commented on templates/tweets/detail.html
> +    <P>いいね数：{{ like_count }}</P>
良いねボタンを押したらlike_countも増えるようにしましょう。

2023-03-05 08:37 UTC, Yamakou621 commented on templates/tweets/home.html
>      <p>投稿者 : {{ tweet.user }}</p>
いいね数も表示してください。

2023-03-05 09:35 UTC, Shiota620 commented on templates/tweets/home.html
>      <p>投稿者 : {{ tweet.user }}</p>
views.pyのhome.pyにlike_countのコンテキストを定義していなかったので繰り返し使う操作としてlike.htmlでいいね数を表示するように変更しました。
この場合、いいね数：をつけると初めは表示されますが、いいねやいいね解除のボタンを押すといいね数：という表記が消え、数字のみになるので初めから数字のみを表示するように変更しました。

2023-03-05 09:42 UTC, Shiota620 commented
commitのメッセージ文を失敗しました。以下補足です。

base.pyif文の修正/いいね数の表記・script.htmlの修正

2023-03-05 13:19 UTC, Yamakou621 reviewed
コメントしました。確認お願いします！

2023-03-05 13:19 UTC, Yamakou621 commented on templates/tweets/detail.html
> +    {% include 'tweets/like.html' %}
DetailViewではcontextにliked_listを渡していないので、詳細画面では常にいいねになってしまうのでは？

2023-03-05 15:43 UTC, Yamakou621 reviewed
これ以外は大丈夫です！

2023-03-05 15:43 UTC, Yamakou621 commented on templates/base.html
> +            <a href="{% url 'welcome:index'%}" class="logout-button">ログアウト</a>
ここはaccounts:logoutです。

2023-03-05 15:43 UTC, Yamakou621 commented on templates/base.html
> +            <a href="{% url 'welcome:index'%}" class="logout-button">ログアウト</a>
LogoutViewのところでtemplate_name="accounts/logout.html"としていますが、logout.htmlを作ってないのでpassで大丈夫です。

2023-03-06 01:28 UTC, masaya09 reviewed
いいねボタンといいね解除ボタンの入れ替えがうまく行ってないです。
ホーム画面でいいね押した後に、いいね押した対象のツイートユーザーのプロフィールページに行った際に、いいねしたのに、いいねボタンが表示されている状態になっています。

2023-03-06 01:47 UTC, masaya09 requested changes
UserProfileView, HomeView, TweetDetailVIewでN＋１が起きてるので対応お願いします

2023-03-06 01:47 UTC, masaya09 commented on tweets/views.py
> +        return context
TweetDetailViewにより、該当ツイートが1つなのは確定しているので、そのツイートをrequest.userがいいねしているかどうか（exist()用いる）をみた方がここではスマートです。その際、変数名はis_likedやhas_likedのようにすると良いです

2023-03-08 03:22 UTC, Shiota620 commented
途中経過です。

N ＋ 1問題の修正に現在取り組んでいるのですが、Homeでいいねボタンを押した際になぜかmessegeのクエリが大量に呼び出されていることに気が付きました。
しかし、私はいいねボタンでmessegeが表示されるようにコードを書いた覚えはありません。
messegeを使用したのはフォロー機能のViewのみだと思うのですがなぜいいねボタンでmessegeが呼び出されているのかが分かりません。
これが解決次第、N+1問題は解決する見込みではあるのですが、その他まだ修正できていないN+1問題があればご指摘お願い致します。

2023-03-08 03:36 UTC, Shiota620 commented
途中経過です。
N＋１問題については現在修正中ですので今しばらくお待ちください。

2023-03-08 09:49 UTC, Shiota620 commented
CIの対処方法が分かりません。

makemigrationsはNo changes detectedが出ます。

これはN+1問題を解決するために迷走していた時にtweets/models.pyに  
  def __str__(self):
        return "{} : {}".format(self.tweet.content, self.user.username)

を追加したことが原因だと考えているんのですがその時はmigrateし直した記憶があります。
いったい何が原因なのか対処方法を教えていただきたいです。

2023-03-08 10:33 UTC, Shiota620 commented
CI対処3

2023-03-08 13:41 UTC, Shiota620 commented
CIのエラーを対処としてmigrateのやり直し５件
git revertの使用２件
これらを試した結果、commitが増えたのと、内容が混ざってしまい、わたしでは対処不可能だと判断した結果、最終手段としてgit resetを使用しました。
申し訳ありません。

2023-03-09 05:05 UTC, masaya09 requested changes

2023-03-09 06:26 UTC, Shiota620 commented on accounts/views.py
> +        context["liked_list"] = liked_list
記述方法を統一の範囲はどの程度が理想なのでしょうか。
例えば、クラス単位で統一もしくはファイル単位で統一することが理想なのか、全てにおいて統一するべきなのか記述方法の統一すべき範囲はどの程度なのでしょうか。

tweet.pyでは途中からcontext={}で複数のコンテキストをまとめて記述できることを知り、違う書き方の練習としてcontext[~]とは違った方法で記述しています。これも、統一したほうが良いでしょうか。

2023-03-09 06:43 UTC, masaya09 commented on accounts/views.py
> +        context["liked_list"] = liked_list
チーム開発等すれば経験しますが、記述を合わせていかないとコードが見にくくなったり、書き方が違うと何か意図があるのではないかと勘ぐります。

合わせられるのなら合わせた方がベストです

2023-03-09 07:38 UTC, Shiota620 commented on accounts/views.py
> +        context["liked_list"] = liked_list
tweets.py のLike/UnlikeViewのcontextを統一しようと検討したのですが、get_context_dataがうまく動作しません。
おかしいと思い、contextについて調べなおしてみたのですが、contextは動的なコンテキストを追加するときと静的なコンテキストを追加するときで、コードの書き方が異なることを知りました。
今まではcontextはhtmlにviewで書いたコードを適用するためのものと認識していたのですが、動的か静的かでコードの書き方が違う場合、私が同じだと認識していたcontext = super().get_context_data(**kwargs)と書いて使うcontext[~]=という書き方と、context={”～”：～}は別物なのでしょうか。

2023-03-09 07:48 UTC, masaya09 commented on accounts/views.py
> +        context["liked_list"] = liked_list
contextはdict型のデータです。LikeのところはViewを継承して用いてるので、get_context_dataは存在しないです。ですので、元のcontextの値がないです。そのため、自分でcontext = {}と定義する必要があります。ここら辺は関数ベースビューと似てますね。context[--]の形で値を入れられたのはcontextというものが定義されてたからということです。詳しくはdict型に値を入れる方法で調べて下さい。これはDjangoではなくpythonの話になります。

2023-03-09 11:12 UTC, masaya09 commented on tweets/views.py
> +        context["unlike_url"] = reverse("tweets:unlike", kwargs={"pk": tweet_id})
LikeとUnlikeは同じ処理ではないので、以前のような記述でOKです

2023-03-09 11:14 UTC, masaya09 commented on tweets/views.py
> +        context["unlike_url"] = reverse("tweets:unlike", kwargs={"pk": tweet_id})
以前のコメントで勘違いさせてしまいましたね。context = {} のところは、ここに値入れていく、つまり前までの記述でOKということになります。context = {...}としておけばよかったかもです

2023-03-09 11:31 UTC, Shiota620 commented on tweets/views.py
> +        context["unlike_url"] = reverse("tweets:unlike", kwargs={"pk": tweet_id})
なるほど。私はcontext[~]に記述を合わせる必要があると思っていたのですが、そもそもlikeとUnlikeは同じ処理ではないため統一する必要はなく、contextもわざわざcontext={}とcontext[～]で分ける必要性はなく、context = {"~":~}のみで完結することが出来るということですね。
今回の件で曖昧だったcontextとpythonのdict型への理解が少し深まった気がします。ありがとうございます。

2023-03-09 11:36 UTC, Shiota620 commented on tweets/views.py
> +        context["unlike_url"] = reverse("tweets:unlike", kwargs={"pk": tweet_id})
なぜか文章に横線が引かれていますが対処方法が分からないので無視して頂けると幸いです。

2023-03-09 11:46 UTC, Shiota620 commented
以前の記述に戻しました。

2023-03-09 11:58 UTC, masaya09 approved these changes
LGTM

2023-03-09 11:59 UTC, merged